ERROR - 2022-03-16 07:45:39 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-03-16 07:45:39 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp2\htdocs\resto\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp2\htdocs\resto\system\Database\BaseBuilder.php(1484): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', NULL, false)
#2 C:\xampp2\htdocs\resto\app\Models\UserModel.php(56): CodeIgniter\Database\BaseBuilder->countAll()
#3 C:\xampp2\htdocs\resto\app\Controllers\Home.php(104): App\Models\UserModel->jumlahUser()
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\Home->home()
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 07:45:39 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp2\htdocs\resto\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp2\\htdoc...', 96, Array)
#1 C:\xampp2\htdocs\resto\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(234): include('C:\\xampp2\\htdoc...')
#3 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-16 11:02:18 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp2\\htdoc...')
#1 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 11:06:33 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp2\\htdoc...')
#1 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 11:06:34 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp2\\htdoc...')
#1 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 11:06:35 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp2\\htdoc...')
#1 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 11:06:35 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp2\\htdoc...')
#1 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 11:06:36 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp2\\htdoc...')
#1 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 11:06:36 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp2\\htdoc...')
#1 C:\xampp2\htdocs\resto\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 11:15:50 --> Invalid file: user/edituser/$id.php
#0 C:\xampp2\htdocs\resto\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/edituser/$...')
#1 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser/$...', Array, true)
#2 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser/$...', Array)
#3 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser()
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#8 {main}
CRITICAL - 2022-03-16 11:23:39 --> Invalid file: user/edituser/$id.php
#0 C:\xampp2\htdocs\resto\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/edituser/$...')
#1 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser/$...', Array, true)
#2 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser/$...', Array)
#3 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser()
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#8 {main}
CRITICAL - 2022-03-16 11:25:17 --> Invalid file: user/edituser/$id.php
#0 C:\xampp2\htdocs\resto\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/edituser/$...')
#1 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser/$...', Array, true)
#2 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser/$...', Array)
#3 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser('1')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#8 {main}
CRITICAL - 2022-03-16 11:25:28 --> Trying to get property 'id_user' of non-object
#0 C:\xampp2\htdocs\resto\app\Views\user\index.php(40): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp2\\htdoc...', 40, Array)
#1 C:\xampp2\htdocs\resto\system\View\View.php(210): include('C:\\xampp2\\htdoc...')
#2 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/index', Array, true)
#4 C:\xampp2\htdocs\resto\app\Controllers\User.php(27): view('user/index', Array)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->index()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#10 {main}
CRITICAL - 2022-03-16 11:25:32 --> Trying to get property 'id_user' of non-object
#0 C:\xampp2\htdocs\resto\app\Views\user\index.php(40): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp2\\htdoc...', 40, Array)
#1 C:\xampp2\htdocs\resto\system\View\View.php(210): include('C:\\xampp2\\htdoc...')
#2 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/index', Array, true)
#4 C:\xampp2\htdocs\resto\app\Controllers\User.php(27): view('user/index', Array)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->index()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#10 {main}
CRITICAL - 2022-03-16 11:25:50 --> Trying to get property 'id_user' of non-object
#0 C:\xampp2\htdocs\resto\app\Views\user\index.php(40): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp2\\htdoc...', 40, Array)
#1 C:\xampp2\htdocs\resto\system\View\View.php(210): include('C:\\xampp2\\htdoc...')
#2 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/index', Array, true)
#4 C:\xampp2\htdocs\resto\app\Controllers\User.php(27): view('user/index', Array)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->index()
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#10 {main}
CRITICAL - 2022-03-16 11:26:48 --> Invalid file: user/edituser/$id.php
#0 C:\xampp2\htdocs\resto\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('user/edituser/$...')
#1 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser/$...', Array, true)
#2 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser/$...', Array)
#3 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser('$value->id_user')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#8 {main}
CRITICAL - 2022-03-16 11:28:49 --> Trying to get property 'id_user' of non-object
#0 C:\xampp2\htdocs\resto\app\Views\user\edituser.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp2\\htdoc...', 17, Array)
#1 C:\xampp2\htdocs\resto\system\View\View.php(210): include('C:\\xampp2\\htdoc...')
#2 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser', Array, true)
#4 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser', Array)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser('$value->id_user')
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#10 {main}
CRITICAL - 2022-03-16 11:30:36 --> Trying to get property 'id_user' of non-object
#0 C:\xampp2\htdocs\resto\app\Views\user\edituser.php(18): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp2\\htdoc...', 18, Array)
#1 C:\xampp2\htdocs\resto\system\View\View.php(210): include('C:\\xampp2\\htdoc...')
#2 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser', Array, true)
#4 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser', Array)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser('$value->id_user')
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#10 {main}
CRITICAL - 2022-03-16 11:32:51 --> syntax error, unexpected '$user' (T_VARIABLE), expecting ',' or ';'
#0 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser', Array, true)
#2 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser', Array)
#3 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser('$value->id_user')
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#8 {main}
CRITICAL - 2022-03-16 11:33:27 --> Trying to get property 'id_user' of non-object
#0 C:\xampp2\htdocs\resto\app\Views\user\edituser.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp2\\htdoc...', 17, Array)
#1 C:\xampp2\htdocs\resto\system\View\View.php(210): include('C:\\xampp2\\htdoc...')
#2 C:\xampp2\htdocs\resto\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp2\htdocs\resto\system\Common.php(1089): CodeIgniter\View\View->render('user/edituser', Array, true)
#4 C:\xampp2\htdocs\resto\app\Controllers\User.php(64): view('user/edituser', Array)
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\User->edituser('$value->id_user')
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#10 {main}
ERROR - 2022-03-16 19:57:59 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-03-16 19:57:59 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp2\htdocs\resto\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp2\htdocs\resto\system\Database\BaseBuilder.php(1484): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', NULL, false)
#2 C:\xampp2\htdocs\resto\app\Models\UserModel.php(56): CodeIgniter\Database\BaseBuilder->countAll()
#3 C:\xampp2\htdocs\resto\app\Controllers\Home.php(104): App\Models\UserModel->jumlahUser()
#4 C:\xampp2\htdocs\resto\system\CodeIgniter.php(825): App\Controllers\Home->home()
#5 C:\xampp2\htdocs\resto\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp2\htdocs\resto\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp2\htdocs\resto\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\xampp2\htdocs\resto\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp2\\htdoc...')
#9 {main}
CRITICAL - 2022-03-16 19:57:59 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp2\htdocs\resto\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp2\\htdoc...', 96, Array)
#1 C:\xampp2\htdocs\resto\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(234): include('C:\\xampp2\\htdoc...')
#3 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp2\htdocs\resto\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
